### PR TITLE
django 3-2

### PR DESCRIPTION
**Pull request by will-moore**
See https://github.com/ome/omero-web/pull/356

To test:

Open an image in vizarr. 
E.g. (user-3):
https://merge-ci.openmicroscopy.org/web/zarr/vizarr/?source=https://merge-ci.openmicroscopy.org/web/zarr/image/200515.zarr

### CODE REVIEW

**Comment by pwalczysko** [comment]
On https://merge-ci.openmicroscopy.org/web/zarr/vizarr/?source=https://merge-ci.openmicroscopy.org/web/zarr/image/200515.zarr all I see is black screen, although vizarr seems to be open.

**Comment by will-moore** [comment]
Ah - I think you're maybe not logged-in (as user-3)?

**Comment by pwalczysko** [comment]
> Ah - I think you're maybe not logged-in (as user-3)?

Yes, thank you , now I can see the image.

**Comment by jburel** [comment]
I can see the image
Screenshot 2022-03-07 at 09 08 15

Unrelated to this PR, having a notification that something is happening instead of a black page will be nice

**Pull request merged**
